// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: one_of/oneof.proto

package one_of

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type A struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *A) Reset() {
	*x = A{}
	mi := &file_one_of_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*A) ProtoMessage() {}

func (x *A) ProtoReflect() protoreflect.Message {
	mi := &file_one_of_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use A.ProtoReflect.Descriptor instead.
func (*A) Descriptor() ([]byte, []int) {
	return file_one_of_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *A) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type B struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *B) Reset() {
	*x = B{}
	mi := &file_one_of_oneof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B) ProtoMessage() {}

func (x *B) ProtoReflect() protoreflect.Message {
	mi := &file_one_of_oneof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B.ProtoReflect.Descriptor instead.
func (*B) Descriptor() ([]byte, []int) {
	return file_one_of_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *B) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Msg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Msg_A
	//	*Msg_B
	Payload       isMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_one_of_oneof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_one_of_oneof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_one_of_oneof_proto_rawDescGZIP(), []int{2}
}

func (x *Msg) GetPayload() isMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Msg) GetA() *A {
	if x != nil {
		if x, ok := x.Payload.(*Msg_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *Msg) GetB() *B {
	if x != nil {
		if x, ok := x.Payload.(*Msg_B); ok {
			return x.B
		}
	}
	return nil
}

type isMsg_Payload interface {
	isMsg_Payload()
}

type Msg_A struct {
	A *A `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type Msg_B struct {
	B *B `protobuf:"bytes,2,opt,name=b,proto3,oneof"`
}

func (*Msg_A) isMsg_Payload() {}

func (*Msg_B) isMsg_Payload() {}

var File_one_of_oneof_proto protoreflect.FileDescriptor

const file_one_of_oneof_proto_rawDesc = "" +
	"\n" +
	"\x12one_of/oneof.proto\x12\x05oneof\"\x13\n" +
	"\x01A\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x17\n" +
	"\x01B\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x03Msg\x12\x18\n" +
	"\x01a\x18\x01 \x01(\v2\b.oneof.AH\x00R\x01a\x12\x18\n" +
	"\x01b\x18\x02 \x01(\v2\b.oneof.BH\x00R\x01bB\t\n" +
	"\apayloadB\bZ\x06one.ofb\x06proto3"

var (
	file_one_of_oneof_proto_rawDescOnce sync.Once
	file_one_of_oneof_proto_rawDescData []byte
)

func file_one_of_oneof_proto_rawDescGZIP() []byte {
	file_one_of_oneof_proto_rawDescOnce.Do(func() {
		file_one_of_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_one_of_oneof_proto_rawDesc), len(file_one_of_oneof_proto_rawDesc)))
	})
	return file_one_of_oneof_proto_rawDescData
}

var file_one_of_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_one_of_oneof_proto_goTypes = []any{
	(*A)(nil),   // 0: oneof.A
	(*B)(nil),   // 1: oneof.B
	(*Msg)(nil), // 2: oneof.Msg
}
var file_one_of_oneof_proto_depIdxs = []int32{
	0, // 0: oneof.Msg.a:type_name -> oneof.A
	1, // 1: oneof.Msg.b:type_name -> oneof.B
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_one_of_oneof_proto_init() }
func file_one_of_oneof_proto_init() {
	if File_one_of_oneof_proto != nil {
		return
	}
	file_one_of_oneof_proto_msgTypes[2].OneofWrappers = []any{
		(*Msg_A)(nil),
		(*Msg_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_one_of_oneof_proto_rawDesc), len(file_one_of_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_one_of_oneof_proto_goTypes,
		DependencyIndexes: file_one_of_oneof_proto_depIdxs,
		MessageInfos:      file_one_of_oneof_proto_msgTypes,
	}.Build()
	File_one_of_oneof_proto = out.File
	file_one_of_oneof_proto_goTypes = nil
	file_one_of_oneof_proto_depIdxs = nil
}
